//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_contact
    {
        public int id { get; set; }
        public string info { get; set; }
        public string address { get; set; }
        public string mail { get; set; }
        public string phonenum { get; set; }
    }
}
