//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopCongNghe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuaHangTestEntities : DbContext
    {
        public CuaHangTestEntities()
            : base("name=CuaHangTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<table_catagory> table_catagory { get; set; }
        public virtual DbSet<table_contact> table_contact { get; set; }
        public virtual DbSet<table_discount> table_discount { get; set; }
        public virtual DbSet<table_footer> table_footer { get; set; }
        public virtual DbSet<table_menu> table_menu { get; set; }
        public virtual DbSet<table_products> table_products { get; set; }
        public virtual DbSet<table_banners> table_banners { get; set; }
        public virtual DbSet<table_login> table_login { get; set; }
    }
}
