//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_footer
    {
        public int id { get; set; }
        public string compname { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public Nullable<bool> hide { get; set; }
        public Nullable<System.DateTime> dateupdate { get; set; }
    }
}
