//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShopCongNghe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_login
    {
        public string userAdmin { get; set; }
        public string passAdmin { get; set; }
        public string hoTen { get; set; }
    }
}
